# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efc963e6b1e58ce1d50dd058271176e9a2aba0ff16ff10793abc6d9fb984fb53ba1ca569c48d475b20a8e68687b5f2997bfa562e4dbe7bdc4a498d369dec12b8

test:
  secret_key_base: 0537f52e93352bc42082b196a06614376016b2b6a0465d7a5d719b1f64af3108991b2cdeae3b5041152213bd8967f77e518bbf6f0a4c7adbdb771cff5b9dcc32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
